// <auto-generated />
using System;
using KayPeyinAn.Api.Products.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KayPeyinAn.Api.Products.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506163452_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KayPeyinAn.Api.Products.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_Category")
                        .HasColumnType("int");

                    b.Property<string>("Product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Product_Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Product_Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            ImageUrl = "assets/images/baguette.png",
                            Product_Category = 0,
                            Product_Description = "Baguette artisanale, croquante à l'extérieur et tendre à l'intérieur.",
                            Product_Name = "Baguette Tradition",
                            Product_Price = 3.37m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            ImageUrl = "assets/images/pain_complet.png",
                            Product_Category = 0,
                            Product_Description = "Pain complet fait maison, riche en fibres et au goût authentique.",
                            Product_Name = "Pain Complet",
                            Product_Price = 1.52m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            ImageUrl = "assets/images/pain_nordique.png",
                            Product_Category = 0,
                            Product_Description = "Pain de Nordique fait maison, avec une mie aérée et une croûte dorée.",
                            Product_Name = "Pain de Nordique",
                            Product_Price = 6.20m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            ImageUrl = "assets/images/beignet_pomme.png",
                            Product_Category = 1,
                            Product_Description = "Beignet aux pommes légèrement sucré, parfait pour un goûter.",
                            Product_Name = "Beignet aux pommes",
                            Product_Price = 4.23m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            ImageUrl = "assets/images/baguette_sesame.png",
                            Product_Category = 0,
                            Product_Description = "Baguette artisanale, croquante à l'extérieur et tendre à l'intérieur.",
                            Product_Name = "Baguette Sésame",
                            Product_Price = 6.36m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            ImageUrl = "assets/images/baguette_graines.png",
                            Product_Category = 0,
                            Product_Description = "Baguette multi-graines, riche en saveurs et idéal pour le petit déjeuner.",
                            Product_Name = "Baguette multi-graines",
                            Product_Price = 3.61m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            ImageUrl = "assets/images/pain_chocolat.png",
                            Product_Category = 0,
                            Product_Description = "Pain de chocolat fondant dans une pâte feuilletée dorée.",
                            Product_Name = "Pain de Chocolat",
                            Product_Price = 5.98m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            ImageUrl = "assets/images/cake_nature.png",
                            Product_Category = 1,
                            Product_Description = "Cake traditionel léger, parfaite pour accompagner le thé.",
                            Product_Name = "Cake nature",
                            Product_Price = 5.76m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            ImageUrl = "assets/images/croissant.png",
                            Product_Category = 0,
                            Product_Description = "Croissant au beurre doré, léger et aéré.",
                            Product_Name = "Croissant Beurre",
                            Product_Price = 2.06m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            ImageUrl = "assets/images/eclair_chocolat.png",
                            Product_Category = 1,
                            Product_Description = "Éclair au chocolat avec une crème pâtissière onctueuse et un glaçage fondant.",
                            Product_Name = "Éclair au Chocolat",
                            Product_Price = 5.80m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 11,
                            Available = true,
                            ImageUrl = "assets/images/macaron_pistache_fraise.png",
                            Product_Category = 1,
                            Product_Description = "Macaron à la framboise avec un coeur crémeux et un goût sucré.",
                            Product_Name = "Macaron Framboise",
                            Product_Price = 5.36m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            Available = true,
                            ImageUrl = "assets/images/tarte_citron.png",
                            Product_Category = 1,
                            Product_Description = "Tartelette au citron acidulée avec une crème légère et une pâte croquante.",
                            Product_Name = "Tartelette Citron",
                            Product_Price = 5.01m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 13,
                            Available = true,
                            ImageUrl = "assets/images/eclair_chocolat.png",
                            Product_Category = 1,
                            Product_Description = "Muffin au chocolat, moelleux et savoureux.",
                            Product_Name = "Muffin Chocolat",
                            Product_Price = 4.46m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 14,
                            Available = true,
                            ImageUrl = "assets/images/tarte_normande.png",
                            Product_Category = 1,
                            Product_Description = "Tarte Normande faite maison avec une pâte sablée et des pommes caramélisées.",
                            Product_Name = "Tarte Normande",
                            Product_Price = 3.79m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 15,
                            Available = true,
                            ImageUrl = "assets/images/tartelette_fraises.png",
                            Product_Category = 1,
                            Product_Description = "Tartelette aux fraises fraîches avec une crème pâtissière légère.",
                            Product_Name = "Tartelette Fraise",
                            Product_Price = 3.50m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 16,
                            Available = true,
                            ImageUrl = "assets/images/pain_raisins.png",
                            Product_Category = 0,
                            Product_Description = "Pain aux raisin, sucrée et fourrée au chocolat fondant dans une pâte feuilletée.",
                            Product_Name = "Pain aux raisins",
                            Product_Price = 2.70m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            Available = true,
                            ImageUrl = "assets/images/madeleine.png",
                            Product_Category = 1,
                            Product_Description = "Madeleine moelleuse au beurre, délicieusement parfumée.",
                            Product_Name = "Madeleine",
                            Product_Price = 1.20m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 18,
                            Available = true,
                            ImageUrl = "assets/images/chausson_pommes.png",
                            Product_Category = 0,
                            Product_Description = "Chausson aux pommes, fait maison avec une pâte feuilletée légère.",
                            Product_Name = "Chausson aux Pommes",
                            Product_Price = 6.35m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 19,
                            Available = true,
                            ImageUrl = "assets/images/sandwich_poulet_avocat.png",
                            Product_Category = 2,
                            Product_Description = "Sandwich au poulet grillé avec une sauce César crémeuse.",
                            Product_Name = "Sandwich Poulet Avocat",
                            Product_Price = 4.23m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 20,
                            Available = true,
                            ImageUrl = "assets/images/tarte_sale.png",
                            Product_Category = 2,
                            Product_Description = "Quiche Lorraine faite maison, avec des lardons, du fromage et des oeufs.",
                            Product_Name = "Quiche Lorraine",
                            Product_Price = 4.36m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 21,
                            Available = true,
                            ImageUrl = "assets/images/pizza.png",
                            Product_Category = 2,
                            Product_Description = "Pizza Margherita avec une sauce tomate maison et de la mozzarella fondante.",
                            Product_Name = "Pizza Margherita",
                            Product_Price = 5.76m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 22,
                            Available = true,
                            ImageUrl = "assets/images/wrap.png",
                            Product_Category = 2,
                            Product_Description = "Wrap garni de saumon fumé, fromage frais et laitue croquante.",
                            Product_Name = "Wrap Saumon",
                            Product_Price = 4.87m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 23,
                            Available = true,
                            ImageUrl = "assets/images/sandwich_jambon_fromage.png",
                            Product_Category = 2,
                            Product_Description = "Sandwich jambon-fromage servi dans une baguette fraîche.",
                            Product_Name = "Sandwich Jambon Fromage",
                            Product_Price = 4.92m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            Available = true,
                            ImageUrl = "assets/images/panini.png",
                            Product_Category = 2,
                            Product_Description = "Panini garnie aux choix.",
                            Product_Name = "Panini",
                            Product_Price = 2.62m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 25,
                            Available = true,
                            ImageUrl = "assets/images/crepe_sucree.png",
                            Product_Category = 2,
                            Product_Description = "Crêpe épaisse et moelleuse, garnie de confiture maison.",
                            Product_Name = "Crêpe sucrée",
                            Product_Price = 2.13m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 26,
                            Available = true,
                            ImageUrl = "assets/images/crepe_salee.png",
                            Product_Category = 2,
                            Product_Description = "Crêpe épaisse et moelleuse.",
                            Product_Name = "Crêpe salée",
                            Product_Price = 6.23m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 27,
                            Available = true,
                            ImageUrl = "assets/images/salade_cesar.png",
                            Product_Category = 2,
                            Product_Description = "Salade César avec poulet grillé, laitue et sauce maison.",
                            Product_Name = "Salade César",
                            Product_Price = 5.39m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 28,
                            Available = true,
                            ImageUrl = "assets/images/tarte_sale.png",
                            Product_Category = 2,
                            Product_Description = "Tartes salées garnies de légumes de saison et d'une pâte feuilletée.",
                            Product_Name = "Tartes Salées",
                            Product_Price = 4.02m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 29,
                            Available = true,
                            ImageUrl = "assets/images/latte_macaron_cafe.png",
                            Product_Category = 3,
                            Product_Description = "Café latte crémeux, fait avec du lait mousseux et un espresso corsé.",
                            Product_Name = "Café Latte",
                            Product_Price = 4.51m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 30,
                            Available = true,
                            ImageUrl = "assets/images/jus_oranges.png",
                            Product_Category = 3,
                            Product_Description = "Jus d'orange frais pressé, plein de vitamines.",
                            Product_Name = "Jus d'Orange Frais",
                            Product_Price = 5.04m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 31,
                            Available = true,
                            ImageUrl = "assets/images/smoothie_fraise.png",
                            Product_Category = 3,
                            Product_Description = "Smoothie aux fraises fraîches, délicieux et rafraîchissant.",
                            Product_Name = "Smoothie Fraise",
                            Product_Price = 6.38m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 32,
                            Available = true,
                            ImageUrl = "assets/images/cafe.png",
                            Product_Category = 3,
                            Product_Description = "Café expresso corsé et intense.",
                            Product_Name = "Café Expresso",
                            Product_Price = 2.41m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 33,
                            Available = true,
                            ImageUrl = "assets/images/cappuccino.png",
                            Product_Category = 3,
                            Product_Description = "Cappuccino onctueux et parfait pour les gourmands.",
                            Product_Name = "Cappuccino",
                            Product_Price = 5.79m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 34,
                            Available = true,
                            ImageUrl = "assets/images/chocolat_chaud.png",
                            Product_Category = 3,
                            Product_Description = "Chocolat chaud crémeux, idéal pour se réchauffer pendant l'hiver.",
                            Product_Name = "Chocolat Chaud",
                            Product_Price = 2.04m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 35,
                            Available = true,
                            ImageUrl = "assets/images/jus_pommes.png",
                            Product_Category = 3,
                            Product_Description = "Jus de pomme naturel.",
                            Product_Name = "Jus de Pomme",
                            Product_Price = 4.23m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 36,
                            Available = true,
                            ImageUrl = "assets/images/pulco_citronnade.png",
                            Product_Category = 3,
                            Product_Description = "Citronnade sucrée et rafraîchissante.",
                            Product_Name = "Pulco citronnade",
                            Product_Price = 1.53m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 37,
                            Available = true,
                            ImageUrl = "assets/images/fuzetea_peche.png",
                            Product_Category = 3,
                            Product_Description = "Thé glacé peche, léger et désaltérant.",
                            Product_Name = "Boisson Thé Glacé",
                            Product_Price = 3.79m,
                            Product_Stock = 100
                        },
                        new
                        {
                            Id = 38,
                            Available = true,
                            ImageUrl = "assets/images/fromage_blanc_pommes.png",
                            Product_Category = 2,
                            Product_Description = "Fromage blanc frais avec sa compote de pommes maison, douce et onctueuse.",
                            Product_Name = "Fromage blanc et compote de pommes",
                            Product_Price = 3.48m,
                            Product_Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
